services:
  - type: web
    name: megalanches-app
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.8
      - key: PORT
        value: 8000
